### ISSUE TITLE
Requests for scripts show pending in Chrome

### ISSUE THREAD

**Issue by tiye** [dead-horse/weekee#1]
Did as it was written in the README: `npm install -g weekee`, run `weekee`,
then I visit the browser, and got this(both for my laptop and VPS, Ubuntu 13.04):
![weekee-issue](https://f.cloud.github.com/assets/449224/727341/b4c5334c-e18b-11e2-8ee3-ebe2cbcdcb20.png)

**Comment by dead-horse** [comment]
升级到最新版，node 0.10+ 用stream2导致static模块出错了
