### ISSUE TITLE
当前weeke 页面的url不可分享

### ISSUE THREAD

**Issue by fengmk2** [dead-horse/weekee#2]
发到旺旺直接悲剧了

![image](https://f.cloud.github.com/assets/156269/1396397/80a3ffd8-3c5f-11e3-99ba-ffb9e2c17bdd.png)

**Comment by dead-horse** [comment]
中文url导致的？

**Comment by fengmk2** [comment]
是的
在 2013-10-24 PM12:58，"dead_horse" notifications@github.com写道：
